version: "3.9"  # optional since v1.27.0
services:
  db:
    image: postgres
    restart: unless-stopped
    environment:
      POSTGRES_PASSWORD: example
      POSTGRES_DB: reactwebscrapper
  api:
    build:
      context: ./backend
    restart: unless-stopped
    depends_on:
      - db
  app:
    build: 
      context: ./frontend
      target: webserver
    restart: unless-stopped
  web:
    image: nginx
    volumes:
    - ./nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
    - "8080:8080"